### ISSUE TITLE
Hindilover International Romanian Addon Problems

### ISSUE THREAD

**Issue by johnsonpaul184** [viorel-m/kingul-repo#1]
Domnule Viorel Kingul,
Sunt foarte bucuros ca am gasit Hindilover Addon pe Indigo Internationals. 
Vreau sa va spun cautarea nu functioneaza, cred ca din cauza liniutelor adaugate in fata si pe la mijlocul numelor de filme si episoade.
Alta problema este la serialul turcesc in difuzare “Fatmagul”. De fiecare data cand se adauga 2, 3 episoade, celelalte de la baza dispar. Cand apasam next dela pagina de 18 episoade, ne duce la alt serial in loc de “fatmagul”. Acuma se vede dela 84 la 101.  Ieri se putea vedea dela 82 la 99
Deocamdata atat am gasit ca nu merge. Va rog sa controlati D-voastra si sa reparati aceasta problema.
Inca odata va multumesc pentru toate addonurile D-voastra.
Suntem romani si locuim in Ohio, si ne plac serialele turcesti.
Cu toata stima, Paul

**Comment by viorel-m** [comment]
O sa incerc sa rezolv problema in zilele urmatoare. E bine ca reclamati, altfel nu pot sa imi dau seama de toate problemele.

**Comment by viorel-m** [comment]
Am rezolvat paginatia.
Cautarea functioneaza, exact asa cum este oferita de site. Daca nu aveti rezultate pe site, nu aveti rezultate nici in Kodi.

**Comment by johnsonpaul184** [comment]
Va multumesc. Ati fost foarte amabil. Merge bine.

Voi mai avea o intrebare, dar nu vreau sa va deranjez de data asta.

Am Kodi 16 pe Amazon Fire TV

Pe curand, Paul

 

  _____

**Comment by johnsonpaul184** [comment]
Domnule Viorel,

Iarasi sunt probleme cu paginatia.

La serialul Aski Memnu si la altele nu se pot obtine paginile pana la
inceputul serialelor. Vorbesc despre Hindilover, Serial turcesc In
desfasurare. Am Fire Tv Box cu Kodi16Jarvis. Va rog sa verificati D-voastra.

Va multumesc, Paul

 

  _____

**Comment by johnsonpaul184** [comment]
Domnule Viorel,

Iarasi sunt probleme cu paginatia.

La serialul Aski Memnu si la altele nu se pot obtine paginile pana la
inceputul serialelor. Vorbesc despre Hindilover, Serial turcesc In
desfasurare. Am Fire Tv Box cu Kodi16Jarvis. Va rog sa verificati D-voastra.

Va multumesc, Paul

 

 

  _____

**Comment by viorel-m** [comment]
Rezolvat in versiunea 1.1.6 @c62f4acaa54e950113c2656ab49dab5453b461cc

**Comment by johnsonpaul184** [comment]
Thank You very much, Paul

 

  _____
